# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 471c85594b930ebbe29d0e770ca0116093d69539c9537ee0055eccee9a5cacdfc31dd992c6e2cce0f2c4540fcf3fa45486d02435144f98d5e076d5081667706b

test:
  secret_key_base: 979da5058a386ccb6cbeb871c9f4df534c681324736e48dc7795cd98383ad1644a77f0e9d73d97772ea29467fce77e39549c8014bb430c6ccd81a3f8d8ccc872

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
